# alias for starting or connecting to screen session
alias scr='TERM=screen-256color screen -dRRA'

alias hivegrep='grep -R --exclude=*.min.js --exclude-dir=lib --exclude-dir=.git --exclude-dir=.cache --exclude-dir=./libsrc/.webassets-cache, --exclude=*.log'

alias whatson='lsof -i'

? () { echo "$*" | bc -l; }

alias git-update-remotes='echo "# Do not edit this file. Edit .gitconfig_base instead" > ~/.gitconfig; cat ~/.gitconfig_base >> ~/.gitconfig; ~/newhive/bin/get_running_webservers.py --format git >> ~/.gitconfig'
