#!/bin/bash

set -eux IFS=" "

dirnames=$(git ls-files | xargs -n 1 dirname | sort | uniq)
for dir in $dirnames; do
  mkdir -p "../$dir"
done


for f in $(git ls-files); do
  cp -r $f "../$f"
done

rm ../install ../update
