#!/bin/bash


set -eu
set IFS=" "

toplevel=$(git ls-files | sed 's/\/.*//' | sort | uniq);
for f in $toplevel; do
  if [[ ! $f =~ ^\..* ]]; then
    echo "$f is not dotfile"
  elif [[ -f $f ]]; then
    if [[ -f "../$f" ]]; then
      echo "copying $f"
      cp "../$f" .
    fi
  elif [[ -d $f ]]; then
    if [[ -d "../$f" ]]; then
      echo "replacing directory $f"
      rm -rf $f
      cp -r "../$f" .
    fi
  else
    echo "not sure what $f is"
  fi
done
