#!/bin/bash


set -eu
set IFS=" "

toplevel=$(git ls-files | sed 's/\/.*//' | sort | uniq);
for f in $toplevel; do
  if [[ ! $f =~ ^\..* ]]; then
    echo "$f is not dotfile"
  elif [[ -f $f ]]; then
    echo "$f is file"
    cp "../$f" .
  elif [[ -d $f ]]; then
    echo "$f is dir"
    rm -rf $f
    cp -r "../$f" .
  else
    echo "not sure what $f is"
  fi
done
