#! /usr/bin/env ruby
require "fileutils"

FileUtils.cd(File.dirname(__FILE__)) do
  files = Dir.glob(".*") - %w{. .. .git .gitignore}
  home = ENV["HOME"]
  print "Copy #{files.join(" ")} from #{home} into #{Dir.pwd} (y/n)? "
  if gets.chomp.downcase == "y"
    FileUtils.rm_rf files
    FileUtils.cp_r files.map{|f| home + "/" + f}, "."
  end
end
